/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as MockCompleteRouteImport } from './routes/mock.complete'
import { Route as MockSessionResultRouteImport } from './routes/mock.session-result'
import { Route as PracticeCustomRouteImport } from './routes/practice.custom'
import { Route as PracticeFigureSequencesRouteImport } from './routes/practice.figure-sequences'
import { Route as PracticeLatinSquaresRouteImport } from './routes/practice.latin-squares'
import { Route as PracticeMathematicalEquationsRouteImport } from './routes/practice.mathematical-equations'
import { Route as PracticeSubjectModuleRouteImport } from './routes/practice.subject-module'
import { Route as MockResultAttemptIdRouteImport } from './routes/mock.result.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const MockCompleteRoute = MockCompleteRouteImport.update({
  id: '/mock/complete',
  path: '/mock/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const MockSessionResultRoute = MockSessionResultRouteImport.update({
  id: '/mock/session-result',
  path: '/mock/session-result',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeCustomRoute = PracticeCustomRouteImport.update({
  id: '/practice/custom',
  path: '/practice/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeFigureSequencesRoute = PracticeFigureSequencesRouteImport.update({
  id: '/practice/figure-sequences',
  path: '/practice/figure-sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeLatinSquaresRoute = PracticeLatinSquaresRouteImport.update({
  id: '/practice/latin-squares',
  path: '/practice/latin-squares',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeMathematicalEquationsRoute =
  PracticeMathematicalEquationsRouteImport.update({
    id: '/practice/mathematical-equations',
    path: '/practice/mathematical-equations',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeSubjectModuleRoute = PracticeSubjectModuleRouteImport.update({
  id: '/practice/subject-module',
  path: '/practice/subject-module',
  getParentRoute: () => rootRouteImport,
} as any)
const MockResultAttemptIdRoute = MockResultAttemptIdRouteImport.update({
  id: '/mock/result/$attemptId',
  path: '/mock/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/feedback': typeof FeedbackRoute
  '/history': typeof HistoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/mock/complete': typeof MockCompleteRoute
  '/mock/session-result': typeof MockSessionResultRoute
  '/practice/custom': typeof PracticeCustomRoute
  '/practice/figure-sequences': typeof PracticeFigureSequencesRoute
  '/practice/latin-squares': typeof PracticeLatinSquaresRoute
  '/practice/mathematical-equations': typeof PracticeMathematicalEquationsRoute
  '/practice/subject-module': typeof PracticeSubjectModuleRoute
  '/admin/': typeof AdminIndexRoute
  '/mock/result/$attemptId': typeof MockResultAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/feedback': typeof FeedbackRoute
  '/history': typeof HistoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/mock/complete': typeof MockCompleteRoute
  '/mock/session-result': typeof MockSessionResultRoute
  '/practice/custom': typeof PracticeCustomRoute
  '/practice/figure-sequences': typeof PracticeFigureSequencesRoute
  '/practice/latin-squares': typeof PracticeLatinSquaresRoute
  '/practice/mathematical-equations': typeof PracticeMathematicalEquationsRoute
  '/practice/subject-module': typeof PracticeSubjectModuleRoute
  '/admin': typeof AdminIndexRoute
  '/mock/result/$attemptId': typeof MockResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/feedback': typeof FeedbackRoute
  '/history': typeof HistoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/mock/complete': typeof MockCompleteRoute
  '/mock/session-result': typeof MockSessionResultRoute
  '/practice/custom': typeof PracticeCustomRoute
  '/practice/figure-sequences': typeof PracticeFigureSequencesRoute
  '/practice/latin-squares': typeof PracticeLatinSquaresRoute
  '/practice/mathematical-equations': typeof PracticeMathematicalEquationsRoute
  '/practice/subject-module': typeof PracticeSubjectModuleRoute
  '/admin/': typeof AdminIndexRoute
  '/mock/result/$attemptId': typeof MockResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cookie-policy'
    | '/disclaimer'
    | '/feedback'
    | '/history'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/home'
    | '/admin/homepage'
    | '/admin/legal'
    | '/admin/questions'
    | '/mock/complete'
    | '/mock/session-result'
    | '/practice/custom'
    | '/practice/figure-sequences'
    | '/practice/latin-squares'
    | '/practice/mathematical-equations'
    | '/practice/subject-module'
    | '/admin/'
    | '/mock/result/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cookie-policy'
    | '/disclaimer'
    | '/feedback'
    | '/history'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/home'
    | '/admin/homepage'
    | '/admin/legal'
    | '/admin/questions'
    | '/mock/complete'
    | '/mock/session-result'
    | '/practice/custom'
    | '/practice/figure-sequences'
    | '/practice/latin-squares'
    | '/practice/mathematical-equations'
    | '/practice/subject-module'
    | '/admin'
    | '/mock/result/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cookie-policy'
    | '/disclaimer'
    | '/feedback'
    | '/history'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/home'
    | '/admin/homepage'
    | '/admin/legal'
    | '/admin/questions'
    | '/mock/complete'
    | '/mock/session-result'
    | '/practice/custom'
    | '/practice/figure-sequences'
    | '/practice/latin-squares'
    | '/practice/mathematical-equations'
    | '/practice/subject-module'
    | '/admin/'
    | '/mock/result/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FeedbackRoute: typeof FeedbackRoute
  HistoryRoute: typeof HistoryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  MockCompleteRoute: typeof MockCompleteRoute
  MockSessionResultRoute: typeof MockSessionResultRoute
  PracticeCustomRoute: typeof PracticeCustomRoute
  PracticeFigureSequencesRoute: typeof PracticeFigureSequencesRoute
  PracticeLatinSquaresRoute: typeof PracticeLatinSquaresRoute
  PracticeMathematicalEquationsRoute: typeof PracticeMathematicalEquationsRoute
  PracticeSubjectModuleRoute: typeof PracticeSubjectModuleRoute
  MockResultAttemptIdRoute: typeof MockResultAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mock/complete': {
      id: '/mock/complete'
      path: '/mock/complete'
      fullPath: '/mock/complete'
      preLoaderRoute: typeof MockCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/session-result': {
      id: '/mock/session-result'
      path: '/mock/session-result'
      fullPath: '/mock/session-result'
      preLoaderRoute: typeof MockSessionResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/custom': {
      id: '/practice/custom'
      path: '/practice/custom'
      fullPath: '/practice/custom'
      preLoaderRoute: typeof PracticeCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/figure-sequences': {
      id: '/practice/figure-sequences'
      path: '/practice/figure-sequences'
      fullPath: '/practice/figure-sequences'
      preLoaderRoute: typeof PracticeFigureSequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/latin-squares': {
      id: '/practice/latin-squares'
      path: '/practice/latin-squares'
      fullPath: '/practice/latin-squares'
      preLoaderRoute: typeof PracticeLatinSquaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/mathematical-equations': {
      id: '/practice/mathematical-equations'
      path: '/practice/mathematical-equations'
      fullPath: '/practice/mathematical-equations'
      preLoaderRoute: typeof PracticeMathematicalEquationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/subject-module': {
      id: '/practice/subject-module'
      path: '/practice/subject-module'
      fullPath: '/practice/subject-module'
      preLoaderRoute: typeof PracticeSubjectModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/result/$attemptId': {
      id: '/mock/result/$attemptId'
      path: '/mock/result/$attemptId'
      fullPath: '/mock/result/$attemptId'
      preLoaderRoute: typeof MockResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  FeedbackRoute: FeedbackRoute,
  HistoryRoute: HistoryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  MockCompleteRoute: MockCompleteRoute,
  MockSessionResultRoute: MockSessionResultRoute,
  PracticeCustomRoute: PracticeCustomRoute,
  PracticeFigureSequencesRoute: PracticeFigureSequencesRoute,
  PracticeLatinSquaresRoute: PracticeLatinSquaresRoute,
  PracticeMathematicalEquationsRoute: PracticeMathematicalEquationsRoute,
  PracticeSubjectModuleRoute: PracticeSubjectModuleRoute,
  MockResultAttemptIdRoute: MockResultAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
