/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as MockCompleteRouteImport } from './routes/mock.complete'
import { Route as MockSessionResultRouteImport } from './routes/mock.session-result'
import { Route as PracticeCustomRouteImport } from './routes/practice.custom'
import { Route as PracticeFigureSequencesRouteImport } from './routes/practice.figure-sequences'
import { Route as PracticeLatinSquaresRouteImport } from './routes/practice.latin-squares'
import { Route as PracticeMathematicalEquationsRouteImport } from './routes/practice.mathematical-equations'
import { Route as PracticeSubjectModuleRouteImport } from './routes/practice.subject-module'
import { Route as MockResultAttemptIdRouteImport } from './routes/mock.result.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const MockCompleteRoute = MockCompleteRouteImport.update({
  id: '/mock/complete',
  path: '/mock/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const MockSessionResultRoute = MockSessionResultRouteImport.update({
  id: '/mock/session-result',
  path: '/mock/session-result',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeCustomRoute = PracticeCustomRouteImport.update({
  id: '/practice/custom',
  path: '/practice/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeFigureSequencesRoute = PracticeFigureSequencesRouteImport.update({
  id: '/practice/figure-sequences',
  path: '/practice/figure-sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeLatinSquaresRoute = PracticeLatinSquaresRouteImport.update({
  id: '/practice/latin-squares',
  path: '/practice/latin-squares',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeMathematicalEquationsRoute =
  PracticeMathematicalEquationsRouteImport.update({
    id: '/practice/mathematical-equations',
    path: '/practice/mathematical-equations',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeSubjectModuleRoute = PracticeSubjectModuleRouteImport.update({
  id: '/practice/subject-module',
  path: '/practice/subject-module',
  getParentRoute: () => rootRouteImport,
} as any)
const MockResultAttemptIdRoute = MockResultAttemptIdRouteImport.update({
  id: '/mock/result/$attemptId',
  path: '/mock/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/mock/complete': typeof MockCompleteRoute
  '/mock/session-result': typeof MockSessionResultRoute
  '/practice/custom': typeof PracticeCustomRoute
  '/practice/figure-sequences': typeof PracticeFigureSequencesRoute
  '/practice/latin-squares': typeof PracticeLatinSquaresRoute
  '/practice/mathematical-equations': typeof PracticeMathematicalEquationsRoute
  '/practice/subject-module': typeof PracticeSubjectModuleRoute
  '/admin/': typeof AdminIndexRoute
  '/mock/result/$attemptId': typeof MockResultAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/mock/complete': typeof MockCompleteRoute
  '/mock/session-result': typeof MockSessionResultRoute
  '/practice/custom': typeof PracticeCustomRoute
  '/practice/figure-sequences': typeof PracticeFigureSequencesRoute
  '/practice/latin-squares': typeof PracticeLatinSquaresRoute
  '/practice/mathematical-equations': typeof PracticeMathematicalEquationsRoute
  '/practice/subject-module': typeof PracticeSubjectModuleRoute
  '/admin': typeof AdminIndexRoute
  '/mock/result/$attemptId': typeof MockResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/mock/complete': typeof MockCompleteRoute
  '/mock/session-result': typeof MockSessionResultRoute
  '/practice/custom': typeof PracticeCustomRoute
  '/practice/figure-sequences': typeof PracticeFigureSequencesRoute
  '/practice/latin-squares': typeof PracticeLatinSquaresRoute
  '/practice/mathematical-equations': typeof PracticeMathematicalEquationsRoute
  '/practice/subject-module': typeof PracticeSubjectModuleRoute
  '/admin/': typeof AdminIndexRoute
  '/mock/result/$attemptId': typeof MockResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/history'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/home'
    | '/admin/questions'
    | '/mock/complete'
    | '/mock/session-result'
    | '/practice/custom'
    | '/practice/figure-sequences'
    | '/practice/latin-squares'
    | '/practice/mathematical-equations'
    | '/practice/subject-module'
    | '/admin/'
    | '/mock/result/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/home'
    | '/admin/questions'
    | '/mock/complete'
    | '/mock/session-result'
    | '/practice/custom'
    | '/practice/figure-sequences'
    | '/practice/latin-squares'
    | '/practice/mathematical-equations'
    | '/practice/subject-module'
    | '/admin'
    | '/mock/result/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/history'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/home'
    | '/admin/questions'
    | '/mock/complete'
    | '/mock/session-result'
    | '/practice/custom'
    | '/practice/figure-sequences'
    | '/practice/latin-squares'
    | '/practice/mathematical-equations'
    | '/practice/subject-module'
    | '/admin/'
    | '/mock/result/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  MockCompleteRoute: typeof MockCompleteRoute
  MockSessionResultRoute: typeof MockSessionResultRoute
  PracticeCustomRoute: typeof PracticeCustomRoute
  PracticeFigureSequencesRoute: typeof PracticeFigureSequencesRoute
  PracticeLatinSquaresRoute: typeof PracticeLatinSquaresRoute
  PracticeMathematicalEquationsRoute: typeof PracticeMathematicalEquationsRoute
  PracticeSubjectModuleRoute: typeof PracticeSubjectModuleRoute
  MockResultAttemptIdRoute: typeof MockResultAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mock/complete': {
      id: '/mock/complete'
      path: '/mock/complete'
      fullPath: '/mock/complete'
      preLoaderRoute: typeof MockCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/session-result': {
      id: '/mock/session-result'
      path: '/mock/session-result'
      fullPath: '/mock/session-result'
      preLoaderRoute: typeof MockSessionResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/custom': {
      id: '/practice/custom'
      path: '/practice/custom'
      fullPath: '/practice/custom'
      preLoaderRoute: typeof PracticeCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/figure-sequences': {
      id: '/practice/figure-sequences'
      path: '/practice/figure-sequences'
      fullPath: '/practice/figure-sequences'
      preLoaderRoute: typeof PracticeFigureSequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/latin-squares': {
      id: '/practice/latin-squares'
      path: '/practice/latin-squares'
      fullPath: '/practice/latin-squares'
      preLoaderRoute: typeof PracticeLatinSquaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/mathematical-equations': {
      id: '/practice/mathematical-equations'
      path: '/practice/mathematical-equations'
      fullPath: '/practice/mathematical-equations'
      preLoaderRoute: typeof PracticeMathematicalEquationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/subject-module': {
      id: '/practice/subject-module'
      path: '/practice/subject-module'
      fullPath: '/practice/subject-module'
      preLoaderRoute: typeof PracticeSubjectModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/result/$attemptId': {
      id: '/mock/result/$attemptId'
      path: '/mock/result/$attemptId'
      fullPath: '/mock/result/$attemptId'
      preLoaderRoute: typeof MockResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  MockCompleteRoute: MockCompleteRoute,
  MockSessionResultRoute: MockSessionResultRoute,
  PracticeCustomRoute: PracticeCustomRoute,
  PracticeFigureSequencesRoute: PracticeFigureSequencesRoute,
  PracticeLatinSquaresRoute: PracticeLatinSquaresRoute,
  PracticeMathematicalEquationsRoute: PracticeMathematicalEquationsRoute,
  PracticeSubjectModuleRoute: PracticeSubjectModuleRoute,
  MockResultAttemptIdRoute: MockResultAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
