-- Migration to import verified real questions from official sources
INSERT INTO public.sources (id, name, publisher, edition, year, license_note, note, question_type)
VALUES ('22222222-2222-2222-2222-222222222222', 'Official General Academic Module PDF', 'g.a.s.t.', '1st', '2026', 'Official Preparatory Material', 'Extracted directly from the official PDF', 'General Academic Module')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.sources (id, name, publisher, edition, year, license_note, note, question_type)
VALUES ('33333333-3333-3333-3333-333333333333', 'PrepDMAT Free Practice', 'PrepDMAT', '1st', '2026', 'Approved Source', 'Extracted from prepdmat.com/practice.html', 'General Academic Module')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Which vector results when the operation s = a + b - c is performed? (a=(1,3), b=(5,1), c=(1,-2))', '[{"id": "a", "text": "s = (5, 6)^T"}, {"id": "b", "text": "s = (7, 2)^T"}, {"id": "c", "text": "s = (5, 2)^T"}, {"id": "d", "text": "s = (7, 6)^T"}]'::jsonb, 'a', 'The vectors are added or subtracted component by component. From the diagram, a = (1,3), b = (5,1), and c = (1, -2), so a + b - c = (1 + 5 - 1, 3 + 1 - (-2)) = (5,6)', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'What statement is true when a vector is multiplied by the number "-2"?', '[{"id": "a", "text": "The length of the vector doubles. The direction of the vector remains the same."}, {"id": "b", "text": "The length of the vector halves. The direction of the vector is reversed."}, {"id": "c", "text": "The length of the vector doubles. The direction of the vector is reversed."}, {"id": "d", "text": "The length of the vector halves. The direction of the vector remains the same."}]'::jsonb, 'c', 'Multiplication by -2 doubles the magnitude of the vector because the absolute value of the scalar is 2. The negative sign reverses the direction of the vector.', 'easy', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'The type of result from the three operations presented in the table is not always the same. Which statement is correct?', '[{"id": "a", "text": "Forming a scalar product results in a scalar; forming a vector product results in a vector; forming a triple product results in a vector."}, {"id": "b", "text": "Forming a scalar product results in a scalar; forming a vector product results in a vector; forming a triple product results in a scalar."}, {"id": "c", "text": "Forming a scalar product results in a vector; forming a vector product results in a vector; forming a triple product results in a scalar."}, {"id": "d", "text": "Forming a scalar product results in a scalar; forming a vector product results in a scalar; forming a triple product results in a scalar."}]'::jsonb, 'b', 'A scalar product results in a scalar, whereas a vector product results in a vector. The triple product combines both operations and finally results in a scalar.', 'easy', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'For the following vectors, the scalar product was calculated. Which result of the calculation is correct? a=(1,2,3)^T, b=(4,5,6)^T', '[{"id": "a", "text": "21"}, {"id": "b", "text": "32"}, {"id": "c", "text": "\u221a14 + \u221a77"}, {"id": "d", "text": "126"}]'::jsonb, 'b', 'The scalar product is calculated by multiplying corresponding components and adding the products: a ⋅ b = 1 ⋅ 4 + 2 ⋅ 5 + 3 ⋅ 6 = 32', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'With the scalar product, it is possible to determine the angle between two vectors. What angle φ is formed between the following two vectors? a = (1, 2)^T, b = (2, 1)^T', '[{"id": "a", "text": "\u03c6 = arccos(4/5)"}, {"id": "b", "text": "\u03c6 = arccos(4/\u221a5)"}, {"id": "c", "text": "\u03c6 = arccos(5/4)"}, {"id": "d", "text": "\u03c6 = arccos(4/\u221a3)"}]'::jsonb, 'a', 'The scalar product is a ⋅ b = 1 ⋅ 2 + 2 ⋅ 1 = 4. Since both vectors have the magnitude √5, cos(φ) = 4 / (√5 ⋅ √5) = 4/5, so φ = arccos(4/5).', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Which vector results when the vector product of the following vectors is determined? a = (3, 2, 1)^T, b = (6, 5, 4)^T', '[{"id": "a", "text": "(3, 6, 3)^T"}, {"id": "b", "text": "(3, -6, 3)^T"}, {"id": "c", "text": "(9, 7, 5)^T"}, {"id": "d", "text": "(18, 10, 4)^T"}]'::jsonb, 'b', 'Using the cross product formula gives a × b = (2 ⋅ 4 − 1 ⋅ 5, 1 ⋅ 6 − 3 ⋅ 4, 3 ⋅ 5 − 2 ⋅ 6) = (3, −6, 3)^T.', 'hard', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'The magnitude of a result vector (vector product) corresponds to the area of the parallelogram spanned. How large is the following area? a=(3,4)^T, b=(1,-2)^T', '[{"id": "a", "text": "\u221a5 square units"}, {"id": "b", "text": "5 square units"}, {"id": "c", "text": "\u221a10 square units"}, {"id": "d", "text": "10 square units"}]'::jsonb, 'd', 'The area of the parallelogram corresponds to the magnitude of the vector product. For the two-dimensional vectors shown, the determinant has the magnitude |3 ⋅ (−2) − 4 ⋅ 1| = 10.', 'hard', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'The triple product can be used to calculate a volume. The volume pertains to the space encompassed by six parallelograms defined by the three vectors. Which statement is correct for all possible cases when the triple product has a value of "0"?', '[{"id": "a", "text": "The vectors lie in a plane."}, {"id": "b", "text": "The vectors are pairwise perpendicular."}, {"id": "c", "text": "The vectors are linearly independent."}, {"id": "d", "text": "The vectors sum up to the zero vector."}]'::jsonb, 'a', 'A triple product of 0 means that the volume of the solid spanned by the three vectors is 0. This is the case when the vectors are coplanar, i.e. when they lie in one plane.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Hydrostatics: A submarine dives to a depth of 10,000 m below sea level. What is the approximate pressure on the hull of the submarine?', '[{"id": "a", "text": "1 bar"}, {"id": "b", "text": "10 bar"}, {"id": "c", "text": "100 bar"}, {"id": "d", "text": "1000 bar"}]'::jsonb, 'd', 'At a depth of 10,000 m, the pressure increases by about 1 bar for every 10 m. This gives approximately 1000 bar, so D is correct.', 'easy', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Hydrostatics: A body with a volume of 2 m³ floats in water. The top edge of the body is 3 m below the water surface, and the bottom edge of the body is 4 m below the water surface. What is the mass of the body?', '[{"id": "a", "text": "1,000 kg"}, {"id": "b", "text": "2,000 kg"}, {"id": "c", "text": "3,000 kg"}, {"id": "d", "text": "4,000 kg"}]'::jsonb, 'b', 'A floating body displaces a mass of water equal to its own mass. With a volume of 2 m³ in water, the displaced mass is about 2000 kg.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Hydrostatics: A ship collides with an iceberg, tearing open the hull 10 m below the waterline. Normally, all spaces in the ship are connected to the outside air through a ventilation system. Just before the collision, the captain had all watertight doors closed, so now neither water nor air can escape from damaged rooms. Only the rectangular space R with a height of 24 m is affected. The tear is right above the floor and is 0.2 m high. What will happen?', '[{"id": "a", "text": "Room R will be completely flooded."}, {"id": "b", "text": "Water will enter room R and rise to about 12 m above the floor."}, {"id": "c", "text": "Water will enter room R and rise to about 0.2 m above the floor."}, {"id": "d", "text": "Nothing, because no water can enter room R through the leak as the air cannot escape."}]'::jsonb, 'b', 'Water can enter because the trapped air is compressed. In the simplified model, the pressure at 10 m depth is about twice atmospheric pressure, so the air volume is reduced by about half and the water rises to around 12 m.', 'hard', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Hydrostatics: A vessel is completely filled with water. The vessel is sealed on top with a rubber membrane. In the water floats an object that is open at the bottom and contains an air bubble at the top. Pressure is to be applied to the water through the rubber membrane. What will happen?', '[{"id": "a", "text": "The object sinks because the water pressure compresses the air bubble, reducing the buoyant force."}, {"id": "b", "text": "The object rises because the water pressure increases the density of the water, and accordingly, the buoyant force increases."}, {"id": "c", "text": "The object does not change its position because water cannot be compressed."}, {"id": "d", "text": "The object is first accelerated downwards by the pressure wave and then rises again until it is back in the same position as at the start."}]'::jsonb, 'a', 'The object contains an air bubble that can be compressed. When pressure is applied to the water, the air bubble becomes smaller, so the object displaces less water. Therefore, the buoyant force decreases and the object sinks.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Hydrostatics: A mechanical pump with a delivery pressure of 3 bar at the pressure port is to pump water from the sea into a tank. The pump sucks water through a suction port by creating a vacuum. Ideal conditions are assumed. Which statement is correct?', '[{"id": "a", "text": "The height of the suction port above sea level (h) must not be greater than the depth of the suction port below sea level (t)."}, {"id": "b", "text": "The height of the suction port above sea level (h) must not exceed 10 m as the pump would otherwise not be able to suck up any water."}, {"id": "c", "text": "The depth of the suction port below sea level (t) must not exceed 20 m as the pump would otherwise not be able to suck up any water."}, {"id": "d", "text": "The total vertical length of the suction port (h + t) must not exceed 30 m as the pump would otherwise not be able to suck up any water."}]'::jsonb, 'b', 'A suction pump can only lift water by using the pressure difference to the atmosphere. Under ideal conditions, atmospheric pressure can lift water by about 10 m, so h must not exceed 10 m.', 'hard', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Hydrostatics: Three ships swim upright. The ships all have the same mass, so they displace the same amount of water and experience the same buoyant force. However, the ships have different cross-sections. All ships have a box with the same mass and dimensions loaded below deck. Now, on all ships, the box is moved the same amount d to the right. As an initial pivot point, the centre of buoyancy B can be assumed. Which statement about the effects is correct?', '[{"id": "a", "text": "Ship A (narrowest) tilts the furthest."}, {"id": "b", "text": "Ship B tilts the furthest."}, {"id": "c", "text": "Ship C (widest) tilts the furthest."}, {"id": "d", "text": "All ships tilt by the same angle."}]'::jsonb, 'a', 'Moving the box creates the same tilting moment in all three ships. The narrowest ship has the smallest restoring effect, so Ship A tilts the furthest.', 'hard', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Optimal Order Quantity: Which statement correctly describes a central assumption of the optimal order quantity model?', '[{"id": "a", "text": "Demand can be reliably forecast and remains stable over the year."}, {"id": "b", "text": "Demand fluctuates, so safety stocks are particularly important."}, {"id": "c", "text": "Quantity discounts are taken into account because larger orders may be cheaper."}, {"id": "d", "text": "The optimal order quantity is chosen so that as little storage space as possible is needed."}]'::jsonb, 'a', 'This is a central assumption of the basic optimal-order-quantity-model: annual demand is known and occurs at a constant rate over time.', 'easy', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Optimal Order Quantity: What could an increase in the optimal order quantity be attributed to?', '[{"id": "a", "text": "A reduction in holding costs per unit per year."}, {"id": "b", "text": "A reduction in ordering costs per order."}, {"id": "c", "text": "A reduction in annual demand."}, {"id": "d", "text": "None of the listed options would explain an increase in the optimal order quantity."}]'::jsonb, 'a', 'A reduction in holding costs leads to a larger optimal order quantity, because keeping inventory becomes cheaper.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Optimal Order Quantity: Why does the model use the following value: Holding Costs = Q/2 * H?', '[{"id": "a", "text": "Because Q/2 is the highest inventory level after an order."}, {"id": "b", "text": "Because Q/2 is the average inventory level between two orders."}, {"id": "c", "text": "Because only half of the products incur holding costs."}, {"id": "d", "text": "Because Q/2 indicates how often orders are placed per year."}]'::jsonb, 'b', 'In the model, inventory is highest immediately after an order arrives (Q) and decreases steadily to 0. So the average inventory level is Q/2.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Optimal Order Quantity: A retailer requires 1,800 units of a specific product annually. Each order placed by the retailer incurs costs of 50 euros. The cost of storing one unit of the product amounts to 2 euros per year. Given this information, which of the following options corresponds to the optimal order quantity that minimises total ordering and holding costs?', '[{"id": "a", "text": "150 units"}, {"id": "b", "text": "300 units"}, {"id": "c", "text": "450 units"}, {"id": "d", "text": "600 units"}]'::jsonb, 'b', 'Q* = sqrt(2 * 1800 * 50 / 2) = sqrt(90000) = 300 units.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Optimal Order Quantity: If the ordering cost per order S is doubled and all other values stay the same, how does the optimal order quantity change?', '[{"id": "a", "text": "It halves."}, {"id": "b", "text": "It doubles."}, {"id": "c", "text": "It quadruples."}, {"id": "d", "text": "It increases by a factor of \u221a2."}]'::jsonb, 'd', 'Doubling S results in Q*_new = sqrt(2D*2S/H) = √2 * Q*. It increases by the square root of 2, which is about 1.41.', 'hard', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Optimal Order Quantity: If the value per unit of the stored product increases, how might this affect the optimal order quantity?', '[{"id": "a", "text": "It could decrease because the annual holding cost per unit might increase."}, {"id": "b", "text": "It could increase because the holding cost rate might increase."}, {"id": "c", "text": "It remains unchanged because the value per unit generally has no influence on Q*."}, {"id": "d", "text": "It could increase because the fixed ordering costs per order decrease as a result."}]'::jsonb, 'a', 'If the value of the product increases, annual holding costs per unit (H) may increase (e.g. capital tied up). Since H is in the denominator, Q* could decrease.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Optimal Order Quantity: A figure shows various costs (A to D) as a function of order quantity. D represents the optimal order quantity. Which line shows the total fixed ordering costs incurred by all orders in one year?', '[{"id": "a", "text": "Line A"}, {"id": "b", "text": "Line B (decreases exponentially)"}, {"id": "c", "text": "Line C (increases linearly)"}, {"id": "d", "text": "Line D (constant)"}]'::jsonb, 'b', 'The total fixed ordering costs per year decrease as the order quantity Q increases, because larger orders mean that fewer orders have to be placed per year.', 'hard', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Research Strategies: How can the following sentence be correctly finished? The deductive research strategy...?', '[{"id": "a", "text": "... requires a certain, fixed sample size, independent of research design."}, {"id": "b", "text": "... focusses on the identification of causal mechanisms."}, {"id": "c", "text": "... examines the relation between factors and effects."}, {"id": "d", "text": "... shows how and why certain conditions influence causes and effects in single cases."}]'::jsonb, 'c', 'The deductive or quantitative strategy aims to identify causal relationships. It therefore examines whether certain factors are related to certain outcomes.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Research Strategies: Which of the following statements applies to the inductive research strategy?', '[{"id": "a", "text": "It is crucial to make statistically proven statements about how well research results scale and are transferable."}, {"id": "b", "text": "It is crucial to examine in which way certain factors have certain consequences."}, {"id": "c", "text": "It is only possible to consider a single case."}, {"id": "d", "text": "Proof about the spread of functioning mechanisms is provided."}]'::jsonb, 'b', 'The inductive or qualitative strategy focuses on causal mechanisms. It examines how and why certain factors lead to certain consequences.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Research Strategies: Which of the following statements about conducting research projects is true?', '[{"id": "a", "text": "In a qualitative research project, the research question can be reformulated during the process."}, {"id": "b", "text": "In a quantitative research project, the sample can be modified in any way after the first data analyses."}, {"id": "c", "text": "In a qualitative research project, changes to the research design do not need to be recorded."}, {"id": "d", "text": "In a quantitative research project, the order of the four phases is not important."}]'::jsonb, 'a', 'Qualitative research can include circular elements. This means that the research question or methodological approach may be refined during the process, as long as changes are documented.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Research Strategies: Which approach most clearly contradicts the ideal-typical process of a quantitative research project?', '[{"id": "a", "text": "In a qualitative study, five teenagers are interviewed... The research question is then refined."}, {"id": "b", "text": "In a qualitative study, five teenagers are interviewed first. Afterwards, further teenagers are included."}, {"id": "c", "text": "For a quantitative study, 500 teenagers are surveyed... The research hypothesis is then retrospectively adapted so that it fits the results."}, {"id": "d", "text": "For a quantitative study, two data collections are planned. The second data collection is carried out according to a previously defined supplementary plan."}]'::jsonb, 'c', 'In a quantitative research project, hypotheses should be defined before data analysis. Changing the hypothesis retrospectively to fit the results contradicts the ideal-typical quantitative process.', 'hard', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Research Strategies: A doctoral student wants to pursue two questions for her dissertation: why young people use the library and what literature they are interested in. She wants to choose a mixed qualitative-quantitative approach. Which procedure might be suitable for her data collection?', '[{"id": "a", "text": "An analysis of the media titles from 1,000 anonymous borrowing records and semi-structured interviews with 4 young people."}, {"id": "b", "text": "A group discussion with 3 young people and an interview with the library director."}, {"id": "c", "text": "A count of all books borrowed by young people over 10 days and an interview with the largest publisher in the city."}, {"id": "d", "text": "A count of the young people entering the library and the evaluation of the city''s population statistics."}]'::jsonb, 'a', 'The borrowing records provide quantitative information about the literature young people are interested in. The interviews can provide qualitative insights into why young people use the library.', 'hard', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'Research Strategies: A master''s student wants to investigate whether certain student behaviours affect productivity. He chooses a well-known theoretical approach and wants to evaluate with statistical methods how far-reaching it is. Which statement applies?', '[{"id": "a", "text": "The student has chosen a deductive approach."}, {"id": "b", "text": "The student must consider possible causal mechanisms in his research design."}, {"id": "c", "text": "The student should conduct targeted individual surveys on campus."}, {"id": "d", "text": "The student cannot use statistical tests because seminar groups are too different."}]'::jsonb, 'a', 'The student starts from an existing theory and wants to test how far the approach applies using statistical methods. This corresponds to a deductive research strategy.', 'medium', '22222222-2222-2222-2222-222222222222', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'A standardised test reports results as percentile ranks: the percentage of all test takers whose score was equal to or lower than yours. In one sitting, 1,600 candidates take the test. Priya''s score is higher than 1,120 of them and equal to none. What is Priya''s percentile rank?', '[{"id": "a", "text": "30"}, {"id": "b", "text": "70"}, {"id": "c", "text": "48"}, {"id": "d", "text": "75"}]'::jsonb, 'b', '1,120 of 1,600 scored lower → 1,120 ÷ 1,600 = 0.70. Percentile rank = 70.', 'medium', '33333333-3333-3333-3333-333333333333', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'A learning study reports: of 240 students who used spaced practice, 168 passed their exam; of 160 students who crammed, 96 passed. Which statement follows from this data?', '[{"id": "a", "text": "Spaced practice caused the higher pass rate"}, {"id": "b", "text": "Most students who passed had crammed"}, {"id": "c", "text": "Fewer than half of the crammers passed"}, {"id": "d", "text": "The pass rate was higher with spaced practice"}]'::jsonb, 'd', '168 ÷ 240 = 70% vs 96 ÷ 160 = 60%. The spaced-practice pass rate is higher.', 'medium', '33333333-3333-3333-3333-333333333333', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'A dMAT test city has 480 available seats across its centres, booked first-come-first-served. If about 5,000 candidates prefer that city, roughly what share of them will have to choose another city?', '[{"id": "a", "text": "About 90%"}, {"id": "b", "text": "About 10%"}, {"id": "c", "text": "About 48%"}, {"id": "d", "text": "Cannot be determined"}]'::jsonb, 'a', '480 of 5,000 preferences can be satisfied: 480 ÷ 5,000 = 9.6% get seats, so roughly 90% must book elsewhere.', 'medium', '33333333-3333-3333-3333-333333333333', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'The dMAT score scale runs 0–200 with a fixed mean of 100 per module. Priya scores 118 on the core module and 96 on the subject module. Which statement follows?', '[{"id": "a", "text": "She answered 118 core questions correctly"}, {"id": "b", "text": "Her overall percentile must be above 50"}, {"id": "c", "text": "Her core result is above average; her subject result is below average"}, {"id": "d", "text": "Her subject performance failed the exam"}]'::jsonb, 'c', 'The 0–200 scale has mean 100, so 118 is above and 96 below average. The score is a conversion, not a raw count.', 'medium', '33333333-3333-3333-3333-333333333333', 90);

INSERT INTO public.questions (module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds)
VALUES ('general_academic', 'In a survey, 500 test takers who used official preparatory materials averaged 112, while 300 who didn''t averaged 104. Which conclusion follows from the data alone?', '[{"id": "a", "text": "On average, users of the official materials scored 8 points higher"}, {"id": "b", "text": "Using the official materials raises a candidate''s score by 8 points"}, {"id": "c", "text": "Every user of the materials outscored every non-user"}, {"id": "d", "text": "Most of the 800 candidates scored above 104"}]'::jsonb, 'a', 'Only the difference in group averages follows from the data.', 'medium', '33333333-3333-3333-3333-333333333333', 90);
