-- ==============================================================================
-- Migration: Seed Official PDF Questions (Text-Based)
-- Description: Inserts 33 text-based questions extracted from the official 
-- General Academic Module Preparatory Materials PDF.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- MODULE: Mathematical Equations
-- ------------------------------------------------------------------------------

INSERT INTO public.questions (id, module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds, subtopic, question_type, content_hash) VALUES
('b0000000-0000-0000-0000-000000000001', 'math_equation', '7 + A = 14\nB - 3 = A\n\nWhat numbers do A and B correspond to so that the equations are solved correctly?', '[{"id": "a", "text": "A=7, B=10"}, {"id": "b", "text": "A=7, B=4"}, {"id": "c", "text": "A=14, B=10"}, {"id": "d", "text": "A=7, B=11"}]'::jsonb, 'a', 'The first equation makes it clear that A = 7 if you subtract 7 on both sides. If you insert this information into the second equation, you get B - 3 = 7. If you add 3 on both sides, you get the solution B = 10.', 'easy', 'aaaaaaaa-0000-0000-0000-000000000001', 75, 'basic_equations', 'system_of_equations', 'math_pdf_01'),
('b0000000-0000-0000-0000-000000000002', 'math_equation', 'B ÷ 2 = A\nB - A = 8\n\nWhat numbers do A and B correspond to so that the equations are solved correctly?', '[{"id": "a", "text": "A=4, B=8"}, {"id": "b", "text": "A=8, B=16"}, {"id": "c", "text": "A=16, B=8"}, {"id": "d", "text": "A=8, B=4"}]'::jsonb, 'b', 'Multiplying by 2 on both sides in the first equation gives B = 2A. Replacing the variable B in the second equation gives 2A - A = 8. This means A = 8. Multiplying both sides by 2 gives B = 16.', 'easy', 'aaaaaaaa-0000-0000-0000-000000000001', 75, 'multiplication_division', 'system_of_equations', 'math_pdf_02'),
('b0000000-0000-0000-0000-000000000003', 'math_equation', '3 × C = A\nA + C = 8\n2 × A + 2 × C = B\n\nWhat numbers do A, B, and C correspond to?', '[{"id": "a", "text": "A=6, B=16, C=2"}, {"id": "b", "text": "A=2, B=16, C=6"}, {"id": "c", "text": "A=6, B=8, C=2"}, {"id": "d", "text": "A=4, B=16, C=4"}]'::jsonb, 'a', 'With the information from the first equation (A = 3C), A can be replaced in the second equation: 3C + C = 8 or 4C = 8 -> C = 2. A = 3 × 2 = 6. B = 2 × 6 + 2 × 2 = 16.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 75, 'substitution_methods', 'system_of_equations', 'math_pdf_03'),
('b0000000-0000-0000-0000-000000000004', 'math_equation', '18 - B = A\n3 × A = C\nB ÷ 2 = A\n\nWhat numbers do A, B, and C correspond to?', '[{"id": "a", "text": "A=6, B=6, C=18"}, {"id": "b", "text": "A=6, B=12, C=18"}, {"id": "c", "text": "A=9, B=9, C=27"}, {"id": "d", "text": "A=12, B=6, C=36"}]'::jsonb, 'b', 'B ÷ 2 = A means B = 2A. Substitute into the first equation: 18 - 2A = A -> 18 = 3A -> A = 6. B = 2 × 6 = 12. C = 3 × 6 = 18.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 75, 'substitution_methods', 'system_of_equations', 'math_pdf_04'),
('b0000000-0000-0000-0000-000000000005', 'math_equation', 'A - B + C - D = 2\n10 × B = C\n5 × B = A\n11 + B = D\n\nWhat numbers do A, B, C, and D correspond to?', '[{"id": "a", "text": "A=5, B=1, C=10, D=12"}, {"id": "b", "text": "A=10, B=2, C=20, D=13"}, {"id": "c", "text": "A=5, B=2, C=10, D=13"}, {"id": "d", "text": "A=15, B=3, C=30, D=14"}]'::jsonb, 'a', 'Insert A, C, and D into the first equation: 5B - B + 10B - (11 + B) = 2. Simplify: 13B - 11 = 2 -> 13B = 13 -> B = 1. Then C=10, A=5, D=12.', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 75, 'substitution_methods', 'system_of_equations', 'math_pdf_05'),
('b0000000-0000-0000-0000-000000000006', 'math_equation', 'C + D - A = 1\n5 × C = D\n13 - C = A\n3 × C - 1 = B\n\nWhat numbers do A, B, C, and D correspond to?', '[{"id": "a", "text": "A=11, B=5, C=2, D=10"}, {"id": "b", "text": "A=10, B=8, C=3, D=15"}, {"id": "c", "text": "A=12, B=2, C=1, D=5"}, {"id": "d", "text": "A=11, B=5, C=3, D=10"}]'::jsonb, 'a', 'Insert into the first equation: C + 5C - (13 - C) = 1 -> 7C - 13 = 1 -> 7C = 14 -> C = 2. D = 10, A = 11, B = 5.', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 75, 'substitution_methods', 'system_of_equations', 'math_pdf_06')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------------------------
-- MODULE: General Academic (Vector Calculations)
-- ------------------------------------------------------------------------------

INSERT INTO public.questions (id, module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds, subtopic, question_type, content_hash) VALUES
('c0000000-0000-0000-0000-000000000001', 'general_academic', 'Given vectors a=(1,3), b=(5,1), and c=(1,-2). Which vector results when the operation s = a + b - c is performed?', '[{"id": "a", "text": "(5, 6)"}, {"id": "b", "text": "(7, 2)"}, {"id": "c", "text": "(5, 2)"}, {"id": "d", "text": "(7, 6)"}]'::jsonb, 'a', 'The vectors are added or subtracted component by component: s = (1 + 5 - 1, 3 + 1 - (-2)) = (5, 6).', 'easy', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'vector_calculations', 'calculation', 'vec_pdf_01'),
('c0000000-0000-0000-0000-000000000002', 'general_academic', 'What statement is true when a vector is multiplied by the number "-2"?', '[{"id": "a", "text": "The length of the vector doubles. The direction of the vector remains the same."}, {"id": "b", "text": "The length of the vector halves. The direction of the vector is reversed."}, {"id": "c", "text": "The length of the vector doubles. The direction of the vector is reversed."}, {"id": "d", "text": "The length of the vector halves. The direction of the vector remains the same."}]'::jsonb, 'c', 'Multiplication by -2 doubles the magnitude of the vector because the absolute value of the scalar is 2. The negative sign reverses the direction of the vector.', 'easy', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'vector_calculations', 'concept', 'vec_pdf_02'),
('c0000000-0000-0000-0000-000000000003', 'general_academic', 'The type of result from the three operations (scalar product, vector product, triple product) is not always the same. Which statement is correct?', '[{"id": "a", "text": "Forming a scalar product results in a scalar; forming a vector product results in a vector; forming a triple product results in a vector."}, {"id": "b", "text": "Forming a scalar product results in a scalar; forming a vector product results in a vector; forming a triple product results in a scalar."}, {"id": "c", "text": "Forming a scalar product results in a vector; forming a vector product results in a vector; forming a triple product results in a scalar."}, {"id": "d", "text": "Forming a scalar product results in a scalar; forming a vector product results in a scalar; forming a triple product results in a scalar."}]'::jsonb, 'b', 'A scalar product results in a scalar, whereas a vector product results in a vector. The triple product combines both operations and finally results in a scalar.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'vector_calculations', 'concept', 'vec_pdf_03'),
('c0000000-0000-0000-0000-000000000004', 'general_academic', 'For the vectors a=(1, 2, 3) and b=(4, 5, 6), the scalar product was calculated. Which result is correct?', '[{"id": "a", "text": "21"}, {"id": "b", "text": "32"}, {"id": "c", "text": "√14 + √77"}, {"id": "d", "text": "126"}]'::jsonb, 'b', 'The scalar product is calculated by multiplying corresponding components and adding the products: 1×4 + 2×5 + 3×6 = 4 + 10 + 18 = 32.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'vector_calculations', 'calculation', 'vec_pdf_04'),
('c0000000-0000-0000-0000-000000000005', 'general_academic', 'With the scalar product, it is possible to determine the angle between two vectors. What angle φ is formed between a=(1, 2) and b=(2, 1)?', '[{"id": "a", "text": "φ = arccos(4/5)"}, {"id": "b", "text": "φ = arccos(4/√5)"}, {"id": "c", "text": "φ = arccos(5/4)"}, {"id": "d", "text": "φ = arccos(4/√3)"}]'::jsonb, 'a', 'The scalar product is 1×2 + 2×1 = 4. Since both vectors have the magnitude √5, cos(φ) = 4 / (√5 × √5) = 4/5. So φ = arccos(4/5).', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'vector_calculations', 'calculation', 'vec_pdf_05'),
('c0000000-0000-0000-0000-000000000006', 'general_academic', 'Which vector results when the vector product of a=(3, 2, 1) and b=(6, 5, 4) is determined?', '[{"id": "a", "text": "(3, 6, 3)"}, {"id": "b", "text": "(3, -6, 3)"}, {"id": "c", "text": "(9, 7, 5)"}, {"id": "d", "text": "(18, 10, 4)"}]'::jsonb, 'b', 'Using the cross product formula gives a × b = (2×4 - 1×5, 1×6 - 3×4, 3×5 - 2×6) = (3, -6, 3).', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'vector_calculations', 'calculation', 'vec_pdf_06'),
('c0000000-0000-0000-0000-000000000007', 'general_academic', 'The magnitude of a result vector (vector product) corresponds to the area of the parallelogram spanned. How large is the area spanned by a=(3, 4) and b=(1, -2)?', '[{"id": "a", "text": "√5 square units"}, {"id": "b", "text": "5 square units"}, {"id": "c", "text": "√10 square units"}, {"id": "d", "text": "10 square units"}]'::jsonb, 'd', 'The area of the parallelogram corresponds to the magnitude of the vector product. For the two-dimensional vectors, the determinant has the magnitude |3 × (-2) - 4 × 1| = |-10| = 10.', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'vector_calculations', 'calculation', 'vec_pdf_07'),
('c0000000-0000-0000-0000-000000000008', 'general_academic', 'The triple product can be used to calculate a volume. Which statement is correct for all possible cases when the triple product has a value of "0"?', '[{"id": "a", "text": "The vectors lie in a plane."}, {"id": "b", "text": "The vectors are pairwise perpendicular."}, {"id": "c", "text": "The vectors are linearly independent."}, {"id": "d", "text": "The vectors sum up to the zero vector."}]'::jsonb, 'a', 'A triple product of 0 means that the volume of the solid spanned by the three vectors is 0. This is the case when the vectors are coplanar, i.e., when they lie in one plane.', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'vector_calculations', 'concept', 'vec_pdf_08')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------------------------
-- MODULE: General Academic (Hydrostatics)
-- ------------------------------------------------------------------------------

INSERT INTO public.questions (id, module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds, subtopic, question_type, content_hash) VALUES
('d0000000-0000-0000-0000-000000000001', 'general_academic', 'A submarine dives to a depth of 10,000 m below sea level. What is the approximate pressure on the hull of the submarine? (Assume water pressure increases by 1 bar every 10 m)', '[{"id": "a", "text": "1 bar"}, {"id": "b", "text": "10 bar"}, {"id": "c", "text": "100 bar"}, {"id": "d", "text": "1000 bar"}]'::jsonb, 'd', 'At a depth of 10,000 m, the pressure increases by about 1 bar for every 10 m. This gives approximately 1000 bar.', 'easy', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'hydrostatics', 'calculation', 'hyd_pdf_01'),
('d0000000-0000-0000-0000-000000000002', 'general_academic', 'A body with a volume of 2 m³ floats in water. The top edge of the body is 3 m below the water surface, and the bottom edge of the body is 4 m below the water surface. What is the mass of the body?', '[{"id": "a", "text": "1,000 kg"}, {"id": "b", "text": "2,000 kg"}, {"id": "c", "text": "3,000 kg"}, {"id": "d", "text": "4,000 kg"}]'::jsonb, 'b', 'A floating body displaces a mass of water equal to its own mass. With a volume of 2 m³ in water, the displaced mass is about 2000 kg.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'hydrostatics', 'calculation', 'hyd_pdf_02'),
('d0000000-0000-0000-0000-000000000003', 'general_academic', 'A ship collides with an iceberg, tearing open the hull 10 m below the waterline. Just before the collision, the captain had all watertight doors closed, so now neither water nor air can escape from damaged rooms. Only the rectangular space R with a height of 24 m is affected. The tear is right above the floor and is 0.2 m high. What will happen?', '[{"id": "a", "text": "Room R will be completely flooded."}, {"id": "b", "text": "Water will enter room R and rise to about 12 m above the floor."}, {"id": "c", "text": "Water will enter room R and rise to about 0.2 m above the floor."}, {"id": "d", "text": "Nothing, because no water can enter room R through the leak as the air cannot escape."}]'::jsonb, 'b', 'Water can enter because the trapped air is compressed. In the simplified model, the pressure at 10 m depth is about twice atmospheric pressure, so the air volume is reduced by about half and the water rises to around 12 m (half of the 24 m room).', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'hydrostatics', 'concept', 'hyd_pdf_03'),
('d0000000-0000-0000-0000-000000000004', 'general_academic', 'A vessel is completely filled with water and sealed on top with a rubber membrane. Inside floats an object open at the bottom containing an air bubble. Pressure is applied to the water through the membrane. What will happen?', '[{"id": "a", "text": "The object sinks because the water pressure compresses the air bubble, reducing the buoyant force."}, {"id": "b", "text": "The object rises because the water pressure increases the density of the water, and accordingly, the buoyant force increases."}, {"id": "c", "text": "The object does not change its position because water cannot be compressed."}, {"id": "d", "text": "The object is first accelerated downwards by the pressure wave and then rises again."}]'::jsonb, 'a', 'The object contains an air bubble that can be compressed. When pressure is applied to the water, the air bubble becomes smaller, so the object displaces less water. Therefore, the buoyant force decreases and the object sinks.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'hydrostatics', 'concept', 'hyd_pdf_04'),
('d0000000-0000-0000-0000-000000000005', 'general_academic', 'A mechanical pump with a delivery pressure of 3 bar sucks water from the sea by creating a vacuum. Which statement is correct?', '[{"id": "a", "text": "The height of the suction port above sea level (h) must not be greater than the depth of the suction port below sea level (t)."}, {"id": "b", "text": "The height of the suction port above sea level (h) must not exceed 10 m as the pump would otherwise not be able to suck up any water."}, {"id": "c", "text": "The depth of the suction port below sea level (t) must not exceed 20 m."}, {"id": "d", "text": "The total vertical length of the suction port (h + t) must not exceed 30 m."}]'::jsonb, 'b', 'A suction pump can only lift water by using the pressure difference to the atmosphere. Under ideal conditions, atmospheric pressure can lift water by about 10 m, so h must not exceed 10 m.', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'hydrostatics', 'concept', 'hyd_pdf_05'),
('d0000000-0000-0000-0000-000000000006', 'general_academic', 'Three ships swim upright and have the same mass and buoyant force. However, they have different cross-sections. Ship A is narrowest, Ship C is widest. On all ships, a box is moved the same amount d to the right. Which statement about the effects is correct?', '[{"id": "a", "text": "Ship A tilts the furthest."}, {"id": "b", "text": "Ship B tilts the furthest."}, {"id": "c", "text": "Ship C tilts the furthest."}, {"id": "d", "text": "All ships tilt by the same angle."}]'::jsonb, 'a', 'Moving the box creates the same tilting moment in all three ships. The narrowest ship has the smallest restoring effect, so Ship A tilts the furthest.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'hydrostatics', 'concept', 'hyd_pdf_06')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------------------------
-- MODULE: General Academic (Optimal Order Quantity)
-- ------------------------------------------------------------------------------

INSERT INTO public.questions (id, module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds, subtopic, question_type, content_hash) VALUES
('e0000000-0000-0000-0000-000000000001', 'general_academic', 'Which statement correctly describes a central assumption of the optimal order quantity model?', '[{"id": "a", "text": "Demand can be reliably forecast and remains stable over the year."}, {"id": "b", "text": "Demand fluctuates, so safety stocks are particularly important."}, {"id": "c", "text": "Quantity discounts are taken into account because larger orders may be cheaper."}, {"id": "d", "text": "The optimal order quantity is chosen so that as little storage space as possible is needed."}]'::jsonb, 'a', 'This is a central assumption of the basic optimal-order-quantity-model: annual demand is known and occurs at a constant rate over time (constant demand).', 'easy', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'optimal_order_quantity', 'concept', 'opt_pdf_01'),
('e0000000-0000-0000-0000-000000000002', 'general_academic', 'What could an increase in the optimal order quantity be attributed to?', '[{"id": "a", "text": "A reduction in holding costs per unit per year."}, {"id": "b", "text": "A reduction in ordering costs per order."}, {"id": "c", "text": "A reduction in annual demand."}, {"id": "d", "text": "None of the listed options would explain an increase."}]'::jsonb, 'a', 'The optimal order quantity Q* = sqrt(2DS/H) increases if: annual demand D increases, ordering cost S increases, or holding cost H decreases. So a reduction in holding costs leads to a larger optimal order quantity.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'optimal_order_quantity', 'concept', 'opt_pdf_02'),
('e0000000-0000-0000-0000-000000000003', 'general_academic', 'Why does the model use the following value: Holding Costs = (Q/2) × H?', '[{"id": "a", "text": "Because Q/2 is the highest inventory level after an order."}, {"id": "b", "text": "Because Q/2 is the average inventory level between two orders."}, {"id": "c", "text": "Because only half of the products incur holding costs."}, {"id": "d", "text": "Because Q/2 indicates how often orders are placed per year."}]'::jsonb, 'b', 'In the model, inventory is highest immediately after an order arrives (Q). It then decreases steadily until it reaches 0. So the average inventory level is Q/2.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'optimal_order_quantity', 'concept', 'opt_pdf_03'),
('e0000000-0000-0000-0000-000000000004', 'general_academic', 'A retailer requires 1,800 units of a specific product annually. Each order placed by the retailer incurs costs of 50 euros. The cost of storing one unit of the product amounts to 2 euros per year. Which corresponds to the optimal order quantity?', '[{"id": "a", "text": "150 units"}, {"id": "b", "text": "300 units"}, {"id": "c", "text": "450 units"}, {"id": "d", "text": "600 units"}]'::jsonb, 'b', 'Using the formula Q* = sqrt(2DS/H) where D=1800, S=50, H=2. Q* = sqrt((2 × 1800 × 50)/2) = sqrt(90000) = 300.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'optimal_order_quantity', 'calculation', 'opt_pdf_04'),
('e0000000-0000-0000-0000-000000000005', 'general_academic', 'If the ordering cost per order S is doubled and all other values stay the same, how does the optimal order quantity change?', '[{"id": "a", "text": "It halves."}, {"id": "b", "text": "It doubles."}, {"id": "c", "text": "It quadruples."}, {"id": "d", "text": "It increases by a factor of √2."}]'::jsonb, 'd', 'Doubling S results in Q*_new = sqrt(2D(2S)/H) = sqrt(2) × sqrt(2DS/H) = √2 × Q*. It increases by about 1.41.', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'optimal_order_quantity', 'calculation', 'opt_pdf_05'),
('e0000000-0000-0000-0000-000000000006', 'general_academic', 'If the value per unit of the stored product increases, how might this affect the optimal order quantity?', '[{"id": "a", "text": "It could decrease because the annual holding cost per unit might increase."}, {"id": "b", "text": "It could increase because the holding cost rate might increase."}, {"id": "c", "text": "It remains unchanged because the value per unit generally has no influence on Q*."}, {"id": "d", "text": "It could increase because the fixed ordering costs per order decrease as a result."}]'::jsonb, 'a', 'H represents the annual holding cost per unit. If the value increases, capital tied up increases and insurance increases, so H increases. Since H is in the denominator, Q* decreases.', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'optimal_order_quantity', 'concept', 'opt_pdf_06'),
('e0000000-0000-0000-0000-000000000007', 'general_academic', 'Which line shows the total fixed ordering costs incurred by all orders in one year? (Line A: u-shaped curve, Line B: curve dropping steadily, Line C: straight line rising, Line D: vertical dashed line for optimal Q)', '[{"id": "a", "text": "Line A"}, {"id": "b", "text": "Line B"}, {"id": "c", "text": "Line C"}, {"id": "d", "text": "Line D"}]'::jsonb, 'b', 'The total fixed ordering costs per year decrease as the order quantity Q increases, because larger orders mean fewer orders placed per year (Line B).', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'optimal_order_quantity', 'concept', 'opt_pdf_07')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------------------------
-- MODULE: General Academic (Research Strategies)
-- ------------------------------------------------------------------------------

INSERT INTO public.questions (id, module, prompt_text, options, correct_option_id, explanation_text, difficulty, source_id, time_estimate_seconds, subtopic, question_type, content_hash) VALUES
('f0000000-0000-0000-0000-000000000001', 'general_academic', 'How can the following sentence be correctly finished? The deductive research strategy...?', '[{"id": "a", "text": "... requires a certain, fixed sample size, independent of research design."}, {"id": "b", "text": "... focusses on the identification of causal mechanisms."}, {"id": "c", "text": "... examines the relation between factors and effects."}, {"id": "d", "text": "... shows how and why certain conditions influence causes and effects in single cases."}]'::jsonb, 'c', 'The deductive or quantitative strategy aims to identify causal relationships. It therefore examines whether certain factors are related to certain outcomes.', 'easy', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'research_strategies', 'concept', 'res_pdf_01'),
('f0000000-0000-0000-0000-000000000002', 'general_academic', 'Which of the following statements applies to the inductive research strategy?', '[{"id": "a", "text": "It is crucial to make statistically proven statements about how well research results scale and are transferable."}, {"id": "b", "text": "It is crucial to examine in which way certain factors have certain consequences."}, {"id": "c", "text": "It is only possible to consider a single case."}, {"id": "d", "text": "Proof about the spread of functioning mechanisms is provided."}]'::jsonb, 'b', 'The inductive or qualitative strategy focuses on causal mechanisms. It examines how and why certain factors lead to certain consequences.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'research_strategies', 'concept', 'res_pdf_02'),
('f0000000-0000-0000-0000-000000000003', 'general_academic', 'Which of the following statements about conducting research projects is true?', '[{"id": "a", "text": "In a qualitative research project, the research question can be reformulated during the process."}, {"id": "b", "text": "In a quantitative research project, the sample can be modified in any way after the first data analyses."}, {"id": "c", "text": "In a qualitative research project, changes to the research design do not need to be recorded."}, {"id": "d", "text": "In a quantitative research project, the order of the four phases is not important."}]'::jsonb, 'a', 'Qualitative research can include circular elements. This means that the research question or methodological approach may be refined during the process, as long as changes are documented.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'research_strategies', 'concept', 'res_pdf_03'),
('f0000000-0000-0000-0000-000000000004', 'general_academic', 'Which approach most clearly contradicts the ideal-typical process of a quantitative research project?', '[{"id": "a", "text": "In a qualitative study, the research question is refined after realizing respondents are introverted."}, {"id": "b", "text": "In a qualitative study, further teenagers are deliberately included later."}, {"id": "c", "text": "For a quantitative study, the research hypothesis is retrospectively adapted so that it fits the results."}, {"id": "d", "text": "For a quantitative study, a second data collection is carried out to balance the sample."}]'::jsonb, 'c', 'In a quantitative research project, hypotheses should be defined before data analysis. Changing the hypothesis retrospectively to fit the results contradicts the ideal-typical quantitative process.', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'research_strategies', 'concept', 'res_pdf_04'),
('f0000000-0000-0000-0000-000000000005', 'general_academic', 'A doctoral student wants to pursue two questions for her dissertation: why young people use the library and what literature they are interested in. She wants a mixed qualitative-quantitative approach. Which procedure is suitable?', '[{"id": "a", "text": "An analysis of the media titles from 1,000 anonymous borrowing records and semi-structured interviews with 4 young people."}, {"id": "b", "text": "A group discussion with 3 young people and an interview with the library director."}, {"id": "c", "text": "A count of all books borrowed over 10 days and an interview with the largest publisher."}, {"id": "d", "text": "A count of the young people entering the library and the evaluation of the city''s population statistics."}]'::jsonb, 'a', 'The borrowing records provide quantitative information about the literature. The interviews provide qualitative insights into why young people use the library.', 'hard', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'research_strategies', 'concept', 'res_pdf_05'),
('f0000000-0000-0000-0000-000000000006', 'general_academic', 'A master''s student wants to investigate whether certain student behaviours affect productivity in seminar groups using a well-known theoretical approach and statistical methods. Which statement applies?', '[{"id": "a", "text": "The student has chosen a deductive approach."}, {"id": "b", "text": "The student must consider possible causal mechanisms in his research design."}, {"id": "c", "text": "The student should conduct targeted individual surveys on campus."}, {"id": "d", "text": "The student cannot use statistical tests because seminar groups are too different."}]'::jsonb, 'a', 'The student starts from an existing theory and wants to test how far the approach applies using statistical methods. This corresponds to a deductive (theory testing) research strategy.', 'medium', 'aaaaaaaa-0000-0000-0000-000000000001', 90, 'research_strategies', 'concept', 'res_pdf_06')
ON CONFLICT (id) DO NOTHING;
